-- Add authentication fields to KHACHHANG table
USE PetCareX;
GO

-- Check and add TenKhachHang (username) column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'TenKhachHang')
BEGIN
    ALTER TABLE KHACHHANG ADD TenKhachHang NVARCHAR(100);
    CREATE UNIQUE INDEX UX_KHACHHANG_TenKhachHang ON KHACHHANG(TenKhachHang);
END
GO

-- Check and add Email column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'Email')
BEGIN
    ALTER TABLE KHACHHANG ADD Email NVARCHAR(255);
    CREATE UNIQUE INDEX UX_KHACHHANG_Email ON KHACHHANG(Email);
END
GO

-- Check and add MatKhau (password) column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'MatKhau')
BEGIN
    ALTER TABLE KHACHHANG ADD MatKhau NVARCHAR(255);
END
GO

-- Check and rename SoDienThoai to SDT if needed
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
           WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'SoDienThoai')
AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'SDT')
BEGIN
    EXEC sp_rename 'KHACHHANG.SoDienThoai', 'SDT', 'COLUMN';
END
GO

-- Check and add NgayTao column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'NgayTao')
BEGIN
    ALTER TABLE KHACHHANG ADD NgayTao DATETIME2 DEFAULT GETDATE();
END
GO

-- Check and add NgayCapNhat column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'NgayCapNhat')
BEGIN
    ALTER TABLE KHACHHANG ADD NgayCapNhat DATETIME2 DEFAULT GETDATE();
END
GO

PRINT 'KHACHHANG table updated with authentication fields successfully!';
GO
