-- PetCareX Database Initialization Script
-- This script will create the database and tables

-- Create database if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'PetCareX')
BEGIN
    CREATE DATABASE PetCareX;
END
GO

-- Switch to the PetCareX database
USE PetCareX;
GO

/*******************************************************************************
 * PHẦN 1: TẠO BẢNG VÀ KHOÁ CHÍNH (PRIMARY KEY)
 ******************************************************************************/

--=============================================================================
-- NHÓM 1: CƠ CẤU TỔ CHỨC & NHÂN SỰ
--=============================================================================

CREATE TABLE CHINHANH (
    MaChiNhanh CHAR(4) NOT NULL,
    TenChiNhanh NVARCHAR(70),
    DiaChi NVARCHAR(150),
    SDT CHAR(10),
    MaQuanLy CHAR(5), -- FK liên kết đến NHANVIEN
    ThoiGianMoCua TIME(0),
    ThoiGianDongCua TIME(0),
    PRIMARY KEY (MaChiNhanh)
);

CREATE TABLE KHO (
    MaKho CHAR(4) NOT NULL,
    NhanVienPhuTrach CHAR(5), -- FK liên kết đến NHANVIEN
    PRIMARY KEY (MaKho)
);

CREATE TABLE KHOA (
    MaKhoa CHAR(2) NOT NULL,
    TenKhoa NVARCHAR(50),
    TruongKhoa CHAR(5), -- FK liên kết đến NHANVIEN
    PRIMARY KEY (MaKhoa)
);

CREATE TABLE LOAINHANVIEN_LUONG (
    LoaiNhanVien NVARCHAR(20) NOT NULL,
    Luong DECIMAL(9, 0),
    PRIMARY KEY (LoaiNhanVien)
);

CREATE TABLE NHANVIEN (
    MaNhanVien CHAR(5) NOT NULL,
    HoTen NVARCHAR(50),
    NgayVaoLam DATE,
    NgayNghiLam DATE,
    NgaySinh DATE,
    SDT CHAR(10),
    MaChiNhanh CHAR(4), -- FK
    LoaiNhanVien NVARCHAR(20), -- FK
    MaKhoa CHAR(2), -- FK
    PRIMARY KEY (MaNhanVien)
);

CREATE TABLE LICHLAMVIECBACSI (
    MaBacSi CHAR(5) NOT NULL, -- FK
    MaChiNhanh CHAR(4) NOT NULL, -- FK
    Ngay DATE NOT NULL,
    TrangThai NVARCHAR(5),
    PRIMARY KEY (MaBacSi, MaChiNhanh, Ngay)
);

--=============================================================================
-- NHÓM 2: KHÁCH HÀNG & THÚ CƯNG
--=============================================================================

CREATE TABLE KHACHHANG (
    MaKhachHang INT IDENTITY(1,1) NOT NULL,
    HoTen NVARCHAR(50),
    SoDienThoai CHAR(10),
    PRIMARY KEY (MaKhachHang)
);

CREATE TABLE HANGTHANHVIEN (
    TenHang NVARCHAR(10) NOT NULL,
    GiamGia DECIMAL(3,2),
    PRIMARY KEY (TenHang)
);

CREATE TABLE KHACHHANGTHANHVIEN (
    MaKhachHang INT NOT NULL, -- Lưu ý: Đề bài yêu cầu IDENTITY riêng, có thể không khớp với KHACHHANG
    Email VARCHAR(50),
    GioiTinh NVARCHAR(3),
    NgaySinh DATE,
    CCCD CHAR(12),
    TongChiTieu DECIMAL(12,2),
    TenHang NVARCHAR(10), -- FK
    DiaChi NVARCHAR(150),
    PRIMARY KEY (MaKhachHang)
);

CREATE TABLE LOAITHUCUNG (
    MaLoaiThuCung CHAR(2) NOT NULL,
    TenLoaiThuCung NVARCHAR(10),
    PRIMARY KEY (MaLoaiThuCung)
);

CREATE TABLE CHUNGLOAITHUCUNG (
    MaChungLoaiThuCung CHAR(2) NOT NULL,
    TenChungLoaiThuCung NVARCHAR(20),
    MaLoaiThuCung CHAR(2), -- FK
    PRIMARY KEY (MaChungLoaiThuCung)
);

CREATE TABLE THUCUNG (
    MaThuCung INT IDENTITY(1, 1) NOT NULL,
    TenThuCung NVARCHAR(20),
    NgaySinhThuCung DATE,
    MaKhachHang INT, -- FK
    MaChungLoai CHAR(2), -- FK
    PRIMARY KEY (MaThuCung)
);

CREATE TABLE LICHHEN (
    MaLichHen INT IDENTITY(1,1) NOT NULL, -- Đã sửa lỗi chính tả INDENTITY
    MaKhachHang INT, -- FK
    MaThuCung INT, -- FK
    MaBacSi CHAR(5), -- FK
    NgayHen DATE,
    GioHen TIME(0),
    TrangThai NVARCHAR(16),
    PRIMARY KEY (MaLichHen)
);

--=============================================================================
-- NHÓM 3: SẢN PHẨM, KHO & VACCINE
--=============================================================================

CREATE TABLE SANPHAM (
    MaSanPham CHAR(5) NOT NULL,
    TenSanPham NVARCHAR(50),
    GiaTienSanPham INT,
    LoaiSanPham NVARCHAR(50),
    PRIMARY KEY (MaSanPham)
);

CREATE TABLE LICHSUGIASANPHAM (
    MaSanPham CHAR(5) NOT NULL, -- FK
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE,
    Gia INT,
    PRIMARY KEY (MaSanPham, NgayBatDau)
);

-- Các bảng kế thừa từ SANPHAM
CREATE TABLE THUOC (
    MaSanPham CHAR(5) NOT NULL, -- FK & PK
    PRIMARY KEY (MaSanPham)
);

CREATE TABLE THUCAN (
    MaSanPham CHAR(5) NOT NULL, -- FK & PK
    PRIMARY KEY (MaSanPham)
);

CREATE TABLE THANHPHANTHUCAN (
    MaSanPham CHAR(5) NOT NULL, -- FK
    ThanhPhan NVARCHAR(20) NOT NULL,
    KhoiLuong FLOAT,
    PRIMARY KEY (MaSanPham, ThanhPhan)
);

CREATE TABLE PHUKIEN (
    MaSanPham CHAR(5) NOT NULL, -- FK & PK
    PRIMARY KEY (MaSanPham)
);

CREATE TABLE CHITIETTONKHO (
    MaKho CHAR(4) NOT NULL, -- FK
    MaSanPham CHAR(5) NOT NULL, -- FK
    SoLuong INT,
    PRIMARY KEY (MaKho, MaSanPham)
);

CREATE TABLE VACCINE (
    MaVaccine CHAR(5) NOT NULL,
    TenVaccine NVARCHAR(20),
    LoaiVaccine NVARCHAR(50),
    GiaVaccine INT,
    PRIMARY KEY (MaVaccine)
);

CREATE TABLE KHO_VACCINE (
    MaKho CHAR(4) NOT NULL, -- FK
    MaVaccine CHAR(5) NOT NULL, -- FK
    PRIMARY KEY (MaKho, MaVaccine)
);

--=============================================================================
-- NHÓM 4: DỊCH VỤ & GÓI TIÊM PHÒNG
--=============================================================================

CREATE TABLE DICHVUYTE (
    MaDichVu CHAR(5) NOT NULL,
    TenDichVu NVARCHAR(50),
    LoaiDichVu NVARCHAR(10),
    PRIMARY KEY (MaDichVu)
);

CREATE TABLE CUNGCAPDICHVU (
    MaChiNhanh CHAR(4) NOT NULL, -- FK
    MaDichVu CHAR(5) NOT NULL, -- FK
    PRIMARY KEY (MaChiNhanh, MaDichVu)
);

CREATE TABLE GOITIEMPHONG (
    MaGoi CHAR(4) NOT NULL,
    TenGoi NVARCHAR(50),
    GiaGoi INT,
    PRIMARY KEY (MaGoi)
);

CREATE TABLE CHITIETGOITIEMPHONG ( 
    MaGoi CHAR(4) NOT NULL, -- FK
    MaVaccine CHAR(5) NOT NULL, -- FK
    SoLuong INT,
    PRIMARY KEY (MaGoi, MaVaccine)
);

CREATE TABLE PHIEUDANGKYTIEMPHONG (
    MaDangKy INT IDENTITY(1, 1) NOT NULL,
    MaKhachHang INT, -- FK
    MaThuCung INT, -- FK
    NgayDangKy DATETIME,
    MaDichVu CHAR(5), -- FK
    PRIMARY KEY (MaDangKy)
);

-- Bảng kế thừa/chi tiết của Phiếu đăng ký
CREATE TABLE PHIEUDANGKYGOI (
    MaDangKy INT NOT NULL, -- FK & PK
    MaGoi CHAR(4), -- FK
    PRIMARY KEY (MaDangKy)
);

CREATE TABLE PHIEUDANGKYLE (
    MaDangKy INT NOT NULL, -- FK & PK
    MaVaccine CHAR(5), -- FK
    PRIMARY KEY (MaDangKy)
);

--=============================================================================
-- NHÓM 5: KHÁM CHỮA BỆNH (QUY TRÌNH NGHIỆP VỤ)
--=============================================================================

CREATE TABLE GIAYKHAMBENHTONGQUAT (
    MaGiayKhamTongQuat INT IDENTITY(1,1) NOT NULL,
    NhietDo FLOAT,
    MoTa NVARCHAR(100),
    MaThuCung INT, -- FK
    MaPhieuDangKyTiemPhong INT, -- FK. Đã sửa từ CHAR(20) sang INT để khớp bảng cha
    PRIMARY KEY (MaGiayKhamTongQuat)
);

CREATE TABLE GIAYKHAMBENHCHUYENKHOA (
    MaGiayKhamChuyenKhoa INT IDENTITY(1,1) NOT NULL, -- Sửa VARCHAR thành CHAR cho thống nhất
    NgayKham DATETIME,
    NgayTaiKham DATETIME,
    MaBacSi CHAR(5), -- FK
    MaThuCung INT, -- FK
    MaDichVu CHAR(5), -- FK. Sửa CHAR(20) thành CHAR(5) khớp DICHVUYTE
    PRIMARY KEY (MaGiayKhamChuyenKhoa)
);

CREATE TABLE CHITIETKHAMBENH_TRIEUCHUNG (
    MaGiayKhamChuyenKhoa INT NOT NULL, -- FK. Sửa VARCHAR thành CHAR
    TrieuChung NVARCHAR(200) NOT NULL,
    PRIMARY KEY (MaGiayKhamChuyenKhoa, TrieuChung)
);

CREATE TABLE CHITIETKHAMBENH_CHUANDOAN (
    MaGiayKhamChuyenKhoa INT NOT NULL, -- FK. Sửa VARCHAR thành CHAR
    ChuanDoan NVARCHAR(200) NOT NULL,
    PRIMARY KEY (MaGiayKhamChuyenKhoa, ChuanDoan)
);

CREATE TABLE TOATHUOC (
    MaToaThuoc INT IDENTITY(1,1) NOT NULL, -- Sửa VARCHAR thành CHAR
    MaThuCung INT, -- FK
    MaBacSi CHAR(5), -- FK
    NgayKham DATETIME,
    TongTien DECIMAL(18,0),
    PRIMARY KEY (MaToaThuoc)
);

CREATE TABLE CHITIETTOATHUOC (
    MaToaThuoc INT NOT NULL, -- FK. Sửa VARCHAR thành CHAR
    MaThuoc CHAR(5) NOT NULL, -- FK. Sửa VARCHAR(20) thành CHAR(5) để khớp SANPHAM/THUOC
    SoLuong INT,
    GhiChu NVARCHAR(100),
    PRIMARY KEY (MaToaThuoc, MaThuoc)
);

CREATE TABLE GIAYTIEMPHONG (
    MaGiayTiem INT IDENTITY(1,1) NOT NULL, -- Sửa VARCHAR thành CHAR
    MaVaccine CHAR(5), -- FK
    MaBacSi CHAR(5), -- FK
    LieuLuong INT,
    NgayTiem DATETIME,
    MaGiayKhamTongQuat INT, -- FK. Sửa VARCHAR(20) thành CHAR(6) khớp GIAYKHAMBENHTONGQUAT
    PRIMARY KEY (MaGiayTiem)
);

--=============================================================================
-- NHÓM 6: HÓA ĐƠN & ĐÁNH GIÁ
--=============================================================================

CREATE TABLE HOADON (
    MaHoaDon INT IDENTITY(1,1) NOT NULL,
    NgayLap DATETIME,
    GiamGia DECIMAL(3,2),
    TongTien DECIMAL(12,2),
    MaNhanVien CHAR(5), -- FK
    MaKhachHang INT, -- FK
    PRIMARY KEY (MaHoaDon)
);

CREATE TABLE HOADON_SANPHAM (
    MaHoaDon INT NOT NULL, -- FK
    MaSanPham CHAR(5) NOT NULL, -- FK
    SoLuong INT,
    PRIMARY KEY (MaHoaDon, MaSanPham)
);

CREATE TABLE THANHTOANDICHVUYTE (
    MaHoaDon INT NOT NULL, -- FK
    MaDichVu CHAR(5) NOT NULL, -- FK
    PRIMARY KEY (MaHoaDon, MaDichVu)
);

CREATE TABLE DANHGIAYTE (
    MaDanhGia INT IDENTITY(1,1) NOT NULL,
    BinhLuan NVARCHAR(200),
    MucDoHaiLong INT,
    ThaiDoNhanVien INT,
    DiemChatLuongDichVu INT,
    MaHoaDon INT, -- FK
    PRIMARY KEY (MaDanhGia)
);

CREATE TABLE DANHGIAMUAHANG (
    MaDanhGia INT IDENTITY(1,1) NOT NULL,
    BinhLuan NVARCHAR(200),
    MaHoaDon INT, -- FK. Đã sửa lỗi chính tả INT00
    MucDoHaiLong INT,
    ThaiDoNhanVien INT,
    PRIMARY KEY (MaDanhGia)
);
GO

/*******************************************************************************
 * PHẦN 2: TẠO KHOÁ NGOẠI (FOREIGN KEY) SỬ DỤNG ALTER TABLE
 ******************************************************************************/

-- NHÓM 1
ALTER TABLE CHINHANH ADD CONSTRAINT FK_CHINHANH_NHANVIEN FOREIGN KEY (MaQuanLy) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE KHO ADD CONSTRAINT FK_KHO_NHANVIEN FOREIGN KEY (NhanVienPhuTrach) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_NHANVIEN FOREIGN KEY (TruongKhoa) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_LOAINV FOREIGN KEY (LoaiNhanVien) REFERENCES LOAINHANVIEN_LUONG(LoaiNhanVien);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_KHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa);
ALTER TABLE LICHLAMVIECBACSI ADD CONSTRAINT FK_LICHBACSI_NHANVIEN FOREIGN KEY (MaBacSi) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE LICHLAMVIECBACSI ADD CONSTRAINT FK_LICHBACSI_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh);

-- NHÓM 2
ALTER TABLE KHACHHANGTHANHVIEN ADD CONSTRAINT FK_KHTV_HANG FOREIGN KEY (TenHang) REFERENCES HANGTHANHVIEN(TenHang);
ALTER TABLE KHACHHANGTHANHVIEN ADD CONSTRAINT FK_KHTV_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang);
ALTER TABLE CHUNGLOAITHUCUNG ADD CONSTRAINT FK_CHUNGLOAI_LOAI FOREIGN KEY (MaLoaiThuCung) REFERENCES LOAITHUCUNG(MaLoaiThuCung);
ALTER TABLE THUCUNG ADD CONSTRAINT FK_THUCUNG_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang);
ALTER TABLE THUCUNG ADD CONSTRAINT FK_THUCUNG_CHUNGLOAI FOREIGN KEY (MaChungLoai) REFERENCES CHUNGLOAITHUCUNG(MaChungLoaiThuCung);
ALTER TABLE LICHHEN ADD CONSTRAINT FK_LICHHEN_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang);
ALTER TABLE LICHHEN ADD CONSTRAINT FK_LICHHEN_THUCUNG FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung);
ALTER TABLE LICHHEN ADD CONSTRAINT FK_LICHHEN_BACSI FOREIGN KEY (MaBacSi) REFERENCES NHANVIEN(MaNhanVien);

-- NHÓM 3
ALTER TABLE LICHSUGIASANPHAM ADD CONSTRAINT FK_LICHSUGIA_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE THUOC ADD CONSTRAINT FK_THUOC_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE THUCAN ADD CONSTRAINT FK_THUCAN_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE THANHPHANTHUCAN ADD CONSTRAINT FK_TPTHUCAN_THUCAN FOREIGN KEY (MaSanPham) REFERENCES THUCAN(MaSanPham);
ALTER TABLE PHUKIEN ADD CONSTRAINT FK_PHUKIEN_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE CHITIETTONKHO ADD CONSTRAINT FK_CTTONKHO_KHO FOREIGN KEY (MaKho) REFERENCES KHO(MaKho);
ALTER TABLE CHITIETTONKHO ADD CONSTRAINT FK_CTTONKHO_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE KHO_VACCINE ADD CONSTRAINT FK_KHOVACCINE_KHO FOREIGN KEY (MaKho) REFERENCES KHO(MaKho);
ALTER TABLE KHO_VACCINE ADD CONSTRAINT FK_KHOVACCINE_VACCINE FOREIGN KEY (MaVaccine) REFERENCES VACCINE(MaVaccine);

-- NHÓM 4
ALTER TABLE CUNGCAPDICHVU ADD CONSTRAINT FK_CCDV_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh);
ALTER TABLE CUNGCAPDICHVU ADD CONSTRAINT FK_CCDV_DICHVU FOREIGN KEY (MaDichVu) REFERENCES DICHVUYTE(MaDichVu);
ALTER TABLE CHITIETGOITIEMPHONG ADD CONSTRAINT FK_CTGOI_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi);
ALTER TABLE CHITIETGOITIEMPHONG ADD CONSTRAINT FK_CTGOI_VACCINE FOREIGN KEY (MaVaccine) REFERENCES VACCINE(MaVaccine);
ALTER TABLE PHIEUDANGKYTIEMPHONG ADD CONSTRAINT FK_PDK_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang);
ALTER TABLE PHIEUDANGKYTIEMPHONG ADD CONSTRAINT FK_PDK_THUCUNG FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung);
ALTER TABLE PHIEUDANGKYTIEMPHONG ADD CONSTRAINT FK_PDK_DICHVU FOREIGN KEY (MaDichVu) REFERENCES DICHVUYTE(MaDichVu);
ALTER TABLE PHIEUDANGKYGOI ADD CONSTRAINT FK_PDKGOI_PDK FOREIGN KEY (MaDangKy) REFERENCES PHIEUDANGKYTIEMPHONG(MaDangKy);
ALTER TABLE PHIEUDANGKYGOI ADD CONSTRAINT FK_PDKGOI_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi);
ALTER TABLE PHIEUDANGKYLE ADD CONSTRAINT FK_PDKLE_PDK FOREIGN KEY (MaDangKy) REFERENCES PHIEUDANGKYTIEMPHONG(MaDangKy);
ALTER TABLE PHIEUDANGKYLE ADD CONSTRAINT FK_PDKLE_VACCINE FOREIGN KEY (MaVaccine) REFERENCES VACCINE(MaVaccine);

-- NHÓM 5
ALTER TABLE GIAYKHAMBENHTONGQUAT ADD CONSTRAINT FK_GKBTQ_THUCUNG FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung);
ALTER TABLE GIAYKHAMBENHTONGQUAT ADD CONSTRAINT FK_GKBTQ_PDK FOREIGN KEY (MaPhieuDangKyTiemPhong) REFERENCES PHIEUDANGKYTIEMPHONG(MaDangKy);
ALTER TABLE GIAYKHAMBENHCHUYENKHOA ADD CONSTRAINT FK_GKBCK_BACSI FOREIGN KEY (MaBacSi) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE GIAYKHAMBENHCHUYENKHOA ADD CONSTRAINT FK_GKBCK_THUCUNG FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung);
ALTER TABLE GIAYKHAMBENHCHUYENKHOA ADD CONSTRAINT FK_GKBCK_DICHVU FOREIGN KEY (MaDichVu) REFERENCES DICHVUYTE(MaDichVu);
ALTER TABLE CHITIETKHAMBENH_TRIEUCHUNG ADD CONSTRAINT FK_CKTC_GKBCK FOREIGN KEY (MaGiayKhamChuyenKhoa) REFERENCES GIAYKHAMBENHCHUYENKHOA(MaGiayKhamChuyenKhoa);
ALTER TABLE CHITIETKHAMBENH_CHUANDOAN ADD CONSTRAINT FK_CKCD_GKBCK FOREIGN KEY (MaGiayKhamChuyenKhoa) REFERENCES GIAYKHAMBENHCHUYENKHOA(MaGiayKhamChuyenKhoa);
ALTER TABLE TOATHUOC ADD CONSTRAINT FK_TOATHUOC_THUCUNG FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung);
ALTER TABLE TOATHUOC ADD CONSTRAINT FK_TOATHUOC_BACSI FOREIGN KEY (MaBacSi) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE CHITIETTOATHUOC ADD CONSTRAINT FK_CTTOA_TOA FOREIGN KEY (MaToaThuoc) REFERENCES TOATHUOC(MaToaThuoc);
-- Giả sử MaThuoc trong chi tiết toa thuốc tham chiếu đến bảng THUOC (sản phẩm là thuốc)
ALTER TABLE CHITIETTOATHUOC ADD CONSTRAINT FK_CTTOA_THUOC FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaSanPham);
ALTER TABLE GIAYTIEMPHONG ADD CONSTRAINT FK_GTP_VACCINE FOREIGN KEY (MaVaccine) REFERENCES VACCINE(MaVaccine);
ALTER TABLE GIAYTIEMPHONG ADD CONSTRAINT FK_GTP_BACSI FOREIGN KEY (MaBacSi) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE GIAYTIEMPHONG ADD CONSTRAINT FK_GTP_GKBTQ FOREIGN KEY (MaGiayKhamTongQuat) REFERENCES GIAYKHAMBENHTONGQUAT(MaGiayKhamTongQuat);

-- NHÓM 6
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang);
ALTER TABLE HOADON_SANPHAM ADD CONSTRAINT FK_HDSP_HOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon);
ALTER TABLE HOADON_SANPHAM ADD CONSTRAINT FK_HDSP_SANPHAM FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham);
ALTER TABLE THANHTOANDICHVUYTE ADD CONSTRAINT FK_TTDV_HOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon);
ALTER TABLE THANHTOANDICHVUYTE ADD CONSTRAINT FK_TTDV_DICHVU FOREIGN KEY (MaDichVu) REFERENCES DICHVUYTE(MaDichVu);
ALTER TABLE DANHGIAYTE ADD CONSTRAINT FK_DGYTE_HOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon);
ALTER TABLE DANHGIAMUAHANG ADD CONSTRAINT FK_DGMH_HOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon);
GO